//
// Created by a6735 on 2020/7/29.
//

#ifndef PCSDL_CONFIG_H
#define PCSDL_CONFIG_H

#define LCD_WIDTH  320
#define LCD_LENGTH 240

#define CACHE_WIDTH  320
#define CACHE_LENGTH 240

#define CACHE_SIZE   CACHE_LENGTH * CACHE_WIDTH

#define BEST_CACHE_LENGTH_BLACK LCD_LENGTH/CACHE_LENGTH
#define BEST_CACHE_WIDTH_BLACK  LCD_WIDTH/CACHE_WIDTH

#endif //PCSDL_CONFIG_H
